server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-logs
    static_configs:
      - targets: ["localhost"]
        labels:
          job: spring-app
          host: docker
          __path__: /logs/*.log*  # container path
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'   # start of log line = timestamp
          max_wait_time: 3s
